### PR TITLE
Allow ubuntu-debug users to less

### PR DESCRIPTION
**Pull request by arosh**
`less` is useful for debugging.

```
$ docker run -it --rm quay.io/cybozu/ubuntu-debug:18.04
root@2bc85e0a5afb:/# cat /proc/meminfo | less
bash: less: command not found
root@2bc85e0a5afb:/#
```

### CODE REVIEW

**Comment by ymmt2005** [comment]
@arosh 
We cannot merge this because of CircleCI restrictions.
Please wait for #39 to be merged.  This PR will need to be rebased afterward.

**Comment by zoetrope** [comment]
@arosh 
#39 was merged.
Please rebase.

**Comment by arosh** [comment]
@zoetrope 
I did it now.

**Review by ymmt2005 — APPROVED** [review]
LGTM

**Pull request merged**
